/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { CompAiCore } from "../core.js";
import { SDKOptions } from "../lib/config.js";
import type { ConsoleLogger } from "./console-logger.js";
import { createRegisterPrompt } from "./prompts.js";
import {
  createRegisterResource,
  createRegisterResourceTemplate,
} from "./resources.js";
import { MCPScope } from "./scopes.js";
import {
  createRegisterTool,
  MCPToolAnnotationFilter,
  registerDynamicTools,
} from "./tools.js";
import { tool$attachmentsAttachmentsControllerCreateAttachmentV1 } from "./tools/attachmentsAttachmentsControllerCreateAttachmentV1.js";
import { tool$attachmentsAttachmentsControllerGetAttachmentDownloadUrlV1 } from "./tools/attachmentsAttachmentsControllerGetAttachmentDownloadUrlV1.js";
import { tool$auditLogsAuditLogControllerGetAuditLogsV1 } from "./tools/auditLogsAuditLogControllerGetAuditLogsV1.js";
import { tool$cloudSecurityCloudSecurityControllerDetectGcpOrgV1 } from "./tools/cloudSecurityCloudSecurityControllerDetectGcpOrgV1.js";
import { tool$cloudSecurityCloudSecurityControllerDetectServicesV1 } from "./tools/cloudSecurityCloudSecurityControllerDetectServicesV1.js";
import { tool$cloudSecurityCloudSecurityControllerGetActivityV1 } from "./tools/cloudSecurityCloudSecurityControllerGetActivityV1.js";
import { tool$cloudSecurityCloudSecurityControllerGetCheckDefinitionV1 } from "./tools/cloudSecurityCloudSecurityControllerGetCheckDefinitionV1.js";
import { tool$cloudSecurityCloudSecurityControllerGetFindingsV1 } from "./tools/cloudSecurityCloudSecurityControllerGetFindingsV1.js";
import { tool$cloudSecurityCloudSecurityControllerGetHistoryV1 } from "./tools/cloudSecurityCloudSecurityControllerGetHistoryV1.js";
import { tool$cloudSecurityCloudSecurityControllerGetProvidersV1 } from "./tools/cloudSecurityCloudSecurityControllerGetProvidersV1.js";
import { tool$cloudSecurityCloudSecurityControllerGetRunStatusV1 } from "./tools/cloudSecurityCloudSecurityControllerGetRunStatusV1.js";
import { tool$cloudSecurityCloudSecurityControllerMarkFindingAsExceptionV1 } from "./tools/cloudSecurityCloudSecurityControllerMarkFindingAsExceptionV1.js";
import { tool$cloudSecurityCloudSecurityControllerResolveGcpSetupStepV1 } from "./tools/cloudSecurityCloudSecurityControllerResolveGcpSetupStepV1.js";
import { tool$cloudSecurityCloudSecurityControllerResolveSessionV1 } from "./tools/cloudSecurityCloudSecurityControllerResolveSessionV1.js";
import { tool$cloudSecurityCloudSecurityControllerRevokeExceptionV1 } from "./tools/cloudSecurityCloudSecurityControllerRevokeExceptionV1.js";
import { tool$cloudSecurityCloudSecurityControllerScanV1 } from "./tools/cloudSecurityCloudSecurityControllerScanV1.js";
import { tool$cloudSecurityCloudSecurityControllerSelectGcpProjectsV1 } from "./tools/cloudSecurityCloudSecurityControllerSelectGcpProjectsV1.js";
import { tool$cloudSecurityCloudSecurityControllerSetupAzureV1 } from "./tools/cloudSecurityCloudSecurityControllerSetupAzureV1.js";
import { tool$cloudSecurityCloudSecurityControllerSetupGcpV1 } from "./tools/cloudSecurityCloudSecurityControllerSetupGcpV1.js";
import { tool$cloudSecurityCloudSecurityControllerTriggerScanV1 } from "./tools/cloudSecurityCloudSecurityControllerTriggerScanV1.js";
import { tool$cloudSecurityCloudSecurityControllerUpdateAwsScanModeV1 } from "./tools/cloudSecurityCloudSecurityControllerUpdateAwsScanModeV1.js";
import { tool$cloudSecurityCloudSecurityControllerValidateAzureV1 } from "./tools/cloudSecurityCloudSecurityControllerValidateAzureV1.js";
import { tool$commentsCommentsControllerCreateCommentV1 } from "./tools/commentsCommentsControllerCreateCommentV1.js";
import { tool$commentsCommentsControllerDeleteCommentV1 } from "./tools/commentsCommentsControllerDeleteCommentV1.js";
import { tool$commentsCommentsControllerGetCommentsV1 } from "./tools/commentsCommentsControllerGetCommentsV1.js";
import { tool$commentsCommentsControllerUpdateCommentV1 } from "./tools/commentsCommentsControllerUpdateCommentV1.js";
import { tool$contextContextControllerCreateContextV1 } from "./tools/contextContextControllerCreateContextV1.js";
import { tool$contextContextControllerDeleteContextV1 } from "./tools/contextContextControllerDeleteContextV1.js";
import { tool$contextContextControllerGetAllContextV1 } from "./tools/contextContextControllerGetAllContextV1.js";
import { tool$contextContextControllerGetContextByIdV1 } from "./tools/contextContextControllerGetContextByIdV1.js";
import { tool$contextContextControllerUpdateContextV1 } from "./tools/contextContextControllerUpdateContextV1.js";
import { tool$deviceAgentDeviceAgentControllerCheckInV1 } from "./tools/deviceAgentDeviceAgentControllerCheckInV1.js";
import { tool$deviceAgentDeviceAgentControllerDownloadMacAgentV1 } from "./tools/deviceAgentDeviceAgentControllerDownloadMacAgentV1.js";
import { tool$deviceAgentDeviceAgentControllerDownloadWindowsAgentV1 } from "./tools/deviceAgentDeviceAgentControllerDownloadWindowsAgentV1.js";
import { tool$deviceAgentDeviceAgentControllerExchangeCodeV1 } from "./tools/deviceAgentDeviceAgentControllerExchangeCodeV1.js";
import { tool$deviceAgentDeviceAgentControllerGenerateAuthCodeV1 } from "./tools/deviceAgentDeviceAgentControllerGenerateAuthCodeV1.js";
import { tool$deviceAgentDeviceAgentControllerGetDeviceStatusV1 } from "./tools/deviceAgentDeviceAgentControllerGetDeviceStatusV1.js";
import { tool$deviceAgentDeviceAgentControllerGetMyOrganizationsV1 } from "./tools/deviceAgentDeviceAgentControllerGetMyOrganizationsV1.js";
import { tool$deviceAgentDeviceAgentControllerGetUpdateFileV1 } from "./tools/deviceAgentDeviceAgentControllerGetUpdateFileV1.js";
import { tool$deviceAgentDeviceAgentControllerHeadUpdateFileV1 } from "./tools/deviceAgentDeviceAgentControllerHeadUpdateFileV1.js";
import { tool$deviceAgentDeviceAgentControllerRegisterDeviceV1 } from "./tools/deviceAgentDeviceAgentControllerRegisterDeviceV1.js";
import { tool$deviceAgentDeviceAgentControllerRevokeAgentAccessV1 } from "./tools/deviceAgentDeviceAgentControllerRevokeAgentAccessV1.js";
import { tool$devicesDevicesControllerDeleteDeviceV1 } from "./tools/devicesDevicesControllerDeleteDeviceV1.js";
import { tool$devicesDevicesControllerGetAllDevicesV1 } from "./tools/devicesDevicesControllerGetAllDevicesV1.js";
import { tool$devicesDevicesControllerGetDevicesByMemberV1 } from "./tools/devicesDevicesControllerGetDevicesByMemberV1.js";
import { tool$evidenceExportAuditorAuditorEvidenceExportControllerExportAllEvidenceV1 } from "./tools/evidenceExportAuditorAuditorEvidenceExportControllerExportAllEvidenceV1.js";
import { tool$evidenceExportEvidenceExportControllerExportAutomationPDFV1 } from "./tools/evidenceExportEvidenceExportControllerExportAutomationPDFV1.js";
import { tool$evidenceExportEvidenceExportControllerExportTaskEvidenceZipV1 } from "./tools/evidenceExportEvidenceExportControllerExportTaskEvidenceZipV1.js";
import { tool$evidenceExportEvidenceExportControllerGetTaskEvidenceSummaryV1 } from "./tools/evidenceExportEvidenceExportControllerGetTaskEvidenceSummaryV1.js";
import { tool$evidenceFormsEvidenceFormsControllerDeleteSubmissionV1 } from "./tools/evidenceFormsEvidenceFormsControllerDeleteSubmissionV1.js";
import { tool$evidenceFormsEvidenceFormsControllerExportCsvV1 } from "./tools/evidenceFormsEvidenceFormsControllerExportCsvV1.js";
import { tool$evidenceFormsEvidenceFormsControllerGetFormSettingsV1 } from "./tools/evidenceFormsEvidenceFormsControllerGetFormSettingsV1.js";
import { tool$evidenceFormsEvidenceFormsControllerGetFormStatusesV1 } from "./tools/evidenceFormsEvidenceFormsControllerGetFormStatusesV1.js";
import { tool$evidenceFormsEvidenceFormsControllerGetFormWithSubmissionsV1 } from "./tools/evidenceFormsEvidenceFormsControllerGetFormWithSubmissionsV1.js";
import { tool$evidenceFormsEvidenceFormsControllerGetMySubmissionsV1 } from "./tools/evidenceFormsEvidenceFormsControllerGetMySubmissionsV1.js";
import { tool$evidenceFormsEvidenceFormsControllerGetPendingSubmissionCountV1 } from "./tools/evidenceFormsEvidenceFormsControllerGetPendingSubmissionCountV1.js";
import { tool$evidenceFormsEvidenceFormsControllerGetSubmissionV1 } from "./tools/evidenceFormsEvidenceFormsControllerGetSubmissionV1.js";
import { tool$evidenceFormsEvidenceFormsControllerListFormsV1 } from "./tools/evidenceFormsEvidenceFormsControllerListFormsV1.js";
import { tool$evidenceFormsEvidenceFormsControllerReviewSubmissionV1 } from "./tools/evidenceFormsEvidenceFormsControllerReviewSubmissionV1.js";
import { tool$evidenceFormsEvidenceFormsControllerSubmitFormV1 } from "./tools/evidenceFormsEvidenceFormsControllerSubmitFormV1.js";
import { tool$evidenceFormsEvidenceFormsControllerUpdateFormSettingV1 } from "./tools/evidenceFormsEvidenceFormsControllerUpdateFormSettingV1.js";
import { tool$evidenceFormsEvidenceFormsControllerUploadFileV1 } from "./tools/evidenceFormsEvidenceFormsControllerUploadFileV1.js";
import { tool$evidenceFormsEvidenceFormsControllerUploadSubmissionV1 } from "./tools/evidenceFormsEvidenceFormsControllerUploadSubmissionV1.js";
import { tool$findingsFindingsControllerCreateFindingV1 } from "./tools/findingsFindingsControllerCreateFindingV1.js";
import { tool$findingsFindingsControllerDeleteFindingV1 } from "./tools/findingsFindingsControllerDeleteFindingV1.js";
import { tool$findingsFindingsControllerGetFindingByIdV1 } from "./tools/findingsFindingsControllerGetFindingByIdV1.js";
import { tool$findingsFindingsControllerGetFindingHistoryV1 } from "./tools/findingsFindingsControllerGetFindingHistoryV1.js";
import { tool$findingsFindingsControllerGetOrganizationFindingsV1 } from "./tools/findingsFindingsControllerGetOrganizationFindingsV1.js";
import { tool$findingsFindingsControllerListFindingsV1 } from "./tools/findingsFindingsControllerListFindingsV1.js";
import { tool$findingsFindingsControllerUpdateFindingV1 } from "./tools/findingsFindingsControllerUpdateFindingV1.js";
import { tool$integrationsChecksControllerListConnectionChecksV1 } from "./tools/integrationsChecksControllerListConnectionChecksV1.js";
import { tool$integrationsChecksControllerListProviderChecksV1 } from "./tools/integrationsChecksControllerListProviderChecksV1.js";
import { tool$integrationsChecksControllerRunConnectionChecksV1 } from "./tools/integrationsChecksControllerRunConnectionChecksV1.js";
import { tool$integrationsChecksControllerRunSingleCheckV1 } from "./tools/integrationsChecksControllerRunSingleCheckV1.js";
import { tool$integrationsConnectionsControllerCreateConnectionV1 } from "./tools/integrationsConnectionsControllerCreateConnectionV1.js";
import { tool$integrationsConnectionsControllerDeleteConnectionV1 } from "./tools/integrationsConnectionsControllerDeleteConnectionV1.js";
import { tool$integrationsConnectionsControllerDisconnectConnectionV1 } from "./tools/integrationsConnectionsControllerDisconnectConnectionV1.js";
import { tool$integrationsConnectionsControllerGetConnectionV1 } from "./tools/integrationsConnectionsControllerGetConnectionV1.js";
import { tool$integrationsConnectionsControllerGetProviderV1 } from "./tools/integrationsConnectionsControllerGetProviderV1.js";
import { tool$integrationsConnectionsControllerListConnectionsV1 } from "./tools/integrationsConnectionsControllerListConnectionsV1.js";
import { tool$integrationsConnectionsControllerListProvidersV1 } from "./tools/integrationsConnectionsControllerListProvidersV1.js";
import { tool$integrationsConnectionsControllerPauseConnectionV1 } from "./tools/integrationsConnectionsControllerPauseConnectionV1.js";
import { tool$integrationsConnectionsControllerResumeConnectionV1 } from "./tools/integrationsConnectionsControllerResumeConnectionV1.js";
import { tool$integrationsConnectionsControllerTestConnectionV1 } from "./tools/integrationsConnectionsControllerTestConnectionV1.js";
import { tool$integrationsConnectionsControllerUpdateConnectionServicesV1 } from "./tools/integrationsConnectionsControllerUpdateConnectionServicesV1.js";
import { tool$integrationsConnectionsControllerUpdateConnectionV1 } from "./tools/integrationsConnectionsControllerUpdateConnectionV1.js";
import { tool$integrationsServicesControllerGetConnectionServicesV1 } from "./tools/integrationsServicesControllerGetConnectionServicesV1.js";
import { tool$integrationsSyncControllerGetAvailableSyncProvidersV1 } from "./tools/integrationsSyncControllerGetAvailableSyncProvidersV1.js";
import { tool$integrationsSyncControllerGetDeviceSyncProviderV1 } from "./tools/integrationsSyncControllerGetDeviceSyncProviderV1.js";
import { tool$integrationsSyncControllerGetEmployeeSyncProviderV1 } from "./tools/integrationsSyncControllerGetEmployeeSyncProviderV1.js";
import { tool$integrationsSyncControllerGetGoogleWorkspaceStatusV1 } from "./tools/integrationsSyncControllerGetGoogleWorkspaceStatusV1.js";
import { tool$integrationsSyncControllerGetJumpCloudStatusV1 } from "./tools/integrationsSyncControllerGetJumpCloudStatusV1.js";
import { tool$integrationsSyncControllerGetRipplingStatusV1 } from "./tools/integrationsSyncControllerGetRipplingStatusV1.js";
import { tool$integrationsSyncControllerSetDeviceSyncProviderV1 } from "./tools/integrationsSyncControllerSetDeviceSyncProviderV1.js";
import { tool$integrationsSyncControllerSetEmployeeSyncProviderV1 } from "./tools/integrationsSyncControllerSetEmployeeSyncProviderV1.js";
import { tool$integrationsSyncControllerSyncDynamicProviderDevicesV1 } from "./tools/integrationsSyncControllerSyncDynamicProviderDevicesV1.js";
import { tool$integrationsSyncControllerSyncDynamicProviderEmployeesV1 } from "./tools/integrationsSyncControllerSyncDynamicProviderEmployeesV1.js";
import { tool$integrationsSyncControllerSyncGoogleWorkspaceEmployeesV1 } from "./tools/integrationsSyncControllerSyncGoogleWorkspaceEmployeesV1.js";
import { tool$integrationsSyncControllerSyncJumpCloudEmployeesV1 } from "./tools/integrationsSyncControllerSyncJumpCloudEmployeesV1.js";
import { tool$integrationsSyncControllerSyncRipplingEmployeesV1 } from "./tools/integrationsSyncControllerSyncRipplingEmployeesV1.js";
import { tool$integrationsTaskIntegrationsControllerDisconnectCheckFromTaskV1 } from "./tools/integrationsTaskIntegrationsControllerDisconnectCheckFromTaskV1.js";
import { tool$integrationsTaskIntegrationsControllerGetChecksForTaskTemplateV1 } from "./tools/integrationsTaskIntegrationsControllerGetChecksForTaskTemplateV1.js";
import { tool$integrationsTaskIntegrationsControllerGetChecksForTaskV1 } from "./tools/integrationsTaskIntegrationsControllerGetChecksForTaskV1.js";
import { tool$integrationsTaskIntegrationsControllerGetTaskCheckRunsV1 } from "./tools/integrationsTaskIntegrationsControllerGetTaskCheckRunsV1.js";
import { tool$integrationsTaskIntegrationsControllerReconnectCheckToTaskV1 } from "./tools/integrationsTaskIntegrationsControllerReconnectCheckToTaskV1.js";
import { tool$integrationsTaskIntegrationsControllerRunCheckForTaskV1 } from "./tools/integrationsTaskIntegrationsControllerRunCheckForTaskV1.js";
import { tool$integrationsTwoFactorSourceControllerGetAvailableTwoFactorSourcesV1 } from "./tools/integrationsTwoFactorSourceControllerGetAvailableTwoFactorSourcesV1.js";
import { tool$integrationsTwoFactorSourceControllerGetTwoFactorSourceV1 } from "./tools/integrationsTwoFactorSourceControllerGetTwoFactorSourceV1.js";
import { tool$integrationsTwoFactorSourceControllerGetTwoFactorStatusesV1 } from "./tools/integrationsTwoFactorSourceControllerGetTwoFactorStatusesV1.js";
import { tool$integrationsTwoFactorSourceControllerSetTwoFactorSourceV1 } from "./tools/integrationsTwoFactorSourceControllerSetTwoFactorSourceV1.js";
import { tool$integrationsVariablesControllerFetchVariableOptionsV1 } from "./tools/integrationsVariablesControllerFetchVariableOptionsV1.js";
import { tool$integrationsVariablesControllerGetConnectionVariablesV1 } from "./tools/integrationsVariablesControllerGetConnectionVariablesV1.js";
import { tool$integrationsVariablesControllerGetProviderVariablesV1 } from "./tools/integrationsVariablesControllerGetProviderVariablesV1.js";
import { tool$integrationsVariablesControllerSaveConnectionVariablesV1 } from "./tools/integrationsVariablesControllerSaveConnectionVariablesV1.js";
import { tool$ismsISMSControllerAddControlsV1 } from "./tools/ismsISMSControllerAddControlsV1.js";
import { tool$ismsISMSControllerApproveV1 } from "./tools/ismsISMSControllerApproveV1.js";
import { tool$ismsISMSControllerDeclineV1 } from "./tools/ismsISMSControllerDeclineV1.js";
import { tool$ismsISMSControllerDriftV1 } from "./tools/ismsISMSControllerDriftV1.js";
import { tool$ismsISMSControllerEnsureSetupV1 } from "./tools/ismsISMSControllerEnsureSetupV1.js";
import { tool$ismsISMSControllerExportDocumentV1 } from "./tools/ismsISMSControllerExportDocumentV1.js";
import { tool$ismsISMSControllerGenerateV1 } from "./tools/ismsISMSControllerGenerateV1.js";
import { tool$ismsISMSControllerGetDocumentV1 } from "./tools/ismsISMSControllerGetDocumentV1.js";
import { tool$ismsISMSControllerGetVersionsV1 } from "./tools/ismsISMSControllerGetVersionsV1.js";
import { tool$ismsISMSControllerRemoveControlV1 } from "./tools/ismsISMSControllerRemoveControlV1.js";
import { tool$ismsISMSControllerSubmitForApprovalV1 } from "./tools/ismsISMSControllerSubmitForApprovalV1.js";
import { tool$ismsISMSProfileControllerGenerateAllV1 } from "./tools/ismsISMSProfileControllerGenerateAllV1.js";
import { tool$ismsISMSProfileControllerGetProfileV1 } from "./tools/ismsISMSProfileControllerGetProfileV1.js";
import { tool$ismsISMSProfileControllerSaveProfileV1 } from "./tools/ismsISMSProfileControllerSaveProfileV1.js";
import { tool$ismsISMSRegistersControllerBulkCreateMeasurementsV1 } from "./tools/ismsISMSRegistersControllerBulkCreateMeasurementsV1.js";
import { tool$ismsISMSRegistersControllerCreateRowV1 } from "./tools/ismsISMSRegistersControllerCreateRowV1.js";
import { tool$ismsISMSRegistersControllerDeleteRowV1 } from "./tools/ismsISMSRegistersControllerDeleteRowV1.js";
import { tool$ismsISMSRegistersControllerSaveNarrativeV1 } from "./tools/ismsISMSRegistersControllerSaveNarrativeV1.js";
import { tool$ismsISMSRegistersControllerUpdateRowV1 } from "./tools/ismsISMSRegistersControllerUpdateRowV1.js";
import { tool$knowledgeBaseKnowledgeBaseControllerCreateRunTokenV1 } from "./tools/knowledgeBaseKnowledgeBaseControllerCreateRunTokenV1.js";
import { tool$knowledgeBaseKnowledgeBaseControllerDeleteAllManualAnswersV1 } from "./tools/knowledgeBaseKnowledgeBaseControllerDeleteAllManualAnswersV1.js";
import { tool$knowledgeBaseKnowledgeBaseControllerDeleteDocumentV1 } from "./tools/knowledgeBaseKnowledgeBaseControllerDeleteDocumentV1.js";
import { tool$knowledgeBaseKnowledgeBaseControllerDeleteManualAnswerV1 } from "./tools/knowledgeBaseKnowledgeBaseControllerDeleteManualAnswerV1.js";
import { tool$knowledgeBaseKnowledgeBaseControllerGetDownloadUrlV1 } from "./tools/knowledgeBaseKnowledgeBaseControllerGetDownloadUrlV1.js";
import { tool$knowledgeBaseKnowledgeBaseControllerGetViewUrlV1 } from "./tools/knowledgeBaseKnowledgeBaseControllerGetViewUrlV1.js";
import { tool$knowledgeBaseKnowledgeBaseControllerListDocumentsV1 } from "./tools/knowledgeBaseKnowledgeBaseControllerListDocumentsV1.js";
import { tool$knowledgeBaseKnowledgeBaseControllerListManualAnswersV1 } from "./tools/knowledgeBaseKnowledgeBaseControllerListManualAnswersV1.js";
import { tool$knowledgeBaseKnowledgeBaseControllerProcessDocumentsV1 } from "./tools/knowledgeBaseKnowledgeBaseControllerProcessDocumentsV1.js";
import { tool$knowledgeBaseKnowledgeBaseControllerSaveManualAnswerV1 } from "./tools/knowledgeBaseKnowledgeBaseControllerSaveManualAnswerV1.js";
import { tool$knowledgeBaseKnowledgeBaseControllerUploadDocumentV1 } from "./tools/knowledgeBaseKnowledgeBaseControllerUploadDocumentV1.js";
import { tool$offboardingChecklistOffboardingChecklistControllerCompleteItemV1 } from "./tools/offboardingChecklistOffboardingChecklistControllerCompleteItemV1.js";
import { tool$offboardingChecklistOffboardingChecklistControllerCreateTemplateItemV1 } from "./tools/offboardingChecklistOffboardingChecklistControllerCreateTemplateItemV1.js";
import { tool$offboardingChecklistOffboardingChecklistControllerDeleteTemplateItemV1 } from "./tools/offboardingChecklistOffboardingChecklistControllerDeleteTemplateItemV1.js";
import { tool$offboardingChecklistOffboardingChecklistControllerExportAllEvidenceV1 } from "./tools/offboardingChecklistOffboardingChecklistControllerExportAllEvidenceV1.js";
import { tool$offboardingChecklistOffboardingChecklistControllerExportEvidenceV1 } from "./tools/offboardingChecklistOffboardingChecklistControllerExportEvidenceV1.js";
import { tool$offboardingChecklistOffboardingChecklistControllerGetAccessRevocationsV1 } from "./tools/offboardingChecklistOffboardingChecklistControllerGetAccessRevocationsV1.js";
import { tool$offboardingChecklistOffboardingChecklistControllerGetMemberChecklistV1 } from "./tools/offboardingChecklistOffboardingChecklistControllerGetMemberChecklistV1.js";
import { tool$offboardingChecklistOffboardingChecklistControllerGetPendingOffboardingsV1 } from "./tools/offboardingChecklistOffboardingChecklistControllerGetPendingOffboardingsV1.js";
import { tool$offboardingChecklistOffboardingChecklistControllerGetTemplateV1 } from "./tools/offboardingChecklistOffboardingChecklistControllerGetTemplateV1.js";
import { tool$offboardingChecklistOffboardingChecklistControllerRevokeAllVendorAccessV1 } from "./tools/offboardingChecklistOffboardingChecklistControllerRevokeAllVendorAccessV1.js";
import { tool$offboardingChecklistOffboardingChecklistControllerRevokeVendorAccessV1 } from "./tools/offboardingChecklistOffboardingChecklistControllerRevokeVendorAccessV1.js";
import { tool$offboardingChecklistOffboardingChecklistControllerUncompleteItemV1 } from "./tools/offboardingChecklistOffboardingChecklistControllerUncompleteItemV1.js";
import { tool$offboardingChecklistOffboardingChecklistControllerUndoVendorRevocationV1 } from "./tools/offboardingChecklistOffboardingChecklistControllerUndoVendorRevocationV1.js";
import { tool$offboardingChecklistOffboardingChecklistControllerUpdateTemplateItemV1 } from "./tools/offboardingChecklistOffboardingChecklistControllerUpdateTemplateItemV1.js";
import { tool$offboardingChecklistOffboardingChecklistControllerUploadEvidenceV1 } from "./tools/offboardingChecklistOffboardingChecklistControllerUploadEvidenceV1.js";
import { tool$organizationOrganizationAccessControllerAutoApproveV1 } from "./tools/organizationOrganizationAccessControllerAutoApproveV1.js";
import { tool$organizationOrganizationControllerCreateApiKeyV1 } from "./tools/organizationOrganizationControllerCreateApiKeyV1.js";
import { tool$organizationOrganizationControllerDeleteOrganizationV1 } from "./tools/organizationOrganizationControllerDeleteOrganizationV1.js";
import { tool$organizationOrganizationControllerGetAvailableScopesV1 } from "./tools/organizationOrganizationControllerGetAvailableScopesV1.js";
import { tool$organizationOrganizationControllerGetOnboardingV1 } from "./tools/organizationOrganizationControllerGetOnboardingV1.js";
import { tool$organizationOrganizationControllerGetOrganizationV1 } from "./tools/organizationOrganizationControllerGetOrganizationV1.js";
import { tool$organizationOrganizationControllerGetPrimaryColorV1 } from "./tools/organizationOrganizationControllerGetPrimaryColorV1.js";
import { tool$organizationOrganizationControllerGetRoleNotificationsV1 } from "./tools/organizationOrganizationControllerGetRoleNotificationsV1.js";
import { tool$organizationOrganizationControllerListApiKeysV1 } from "./tools/organizationOrganizationControllerListApiKeysV1.js";
import { tool$organizationOrganizationControllerRemoveLogoV1 } from "./tools/organizationOrganizationControllerRemoveLogoV1.js";
import { tool$organizationOrganizationControllerRevokeApiKeyV1 } from "./tools/organizationOrganizationControllerRevokeApiKeyV1.js";
import { tool$organizationOrganizationControllerTransferOwnershipV1 } from "./tools/organizationOrganizationControllerTransferOwnershipV1.js";
import { tool$organizationOrganizationControllerUpdateOrganizationV1 } from "./tools/organizationOrganizationControllerUpdateOrganizationV1.js";
import { tool$organizationOrganizationControllerUpdateRoleNotificationsV1 } from "./tools/organizationOrganizationControllerUpdateRoleNotificationsV1.js";
import { tool$organizationOrganizationControllerUploadLogoV1 } from "./tools/organizationOrganizationControllerUploadLogoV1.js";
import { tool$orgChartOrgChartControllerDeleteOrgChartV1 } from "./tools/orgChartOrgChartControllerDeleteOrgChartV1.js";
import { tool$orgChartOrgChartControllerGetOrgChartV1 } from "./tools/orgChartOrgChartControllerGetOrgChartV1.js";
import { tool$orgChartOrgChartControllerUploadOrgChartV1 } from "./tools/orgChartOrgChartControllerUploadOrgChartV1.js";
import { tool$orgChartOrgChartControllerUpsertOrgChartV1 } from "./tools/orgChartOrgChartControllerUpsertOrgChartV1.js";
import { tool$peoplePeopleControllerBulkCreateMembersV1 } from "./tools/peoplePeopleControllerBulkCreateMembersV1.js";
import { tool$peoplePeopleControllerCreateMemberV1 } from "./tools/peoplePeopleControllerCreateMemberV1.js";
import { tool$peoplePeopleControllerDeleteEmploymentEvidenceV1 } from "./tools/peoplePeopleControllerDeleteEmploymentEvidenceV1.js";
import { tool$peoplePeopleControllerDeleteMemberV1 } from "./tools/peoplePeopleControllerDeleteMemberV1.js";
import { tool$peoplePeopleControllerGetAllPeopleV1 } from "./tools/peoplePeopleControllerGetAllPeopleV1.js";
import { tool$peoplePeopleControllerGetDevicesV1 } from "./tools/peoplePeopleControllerGetDevicesV1.js";
import { tool$peoplePeopleControllerGetEmailPreferencesV1 } from "./tools/peoplePeopleControllerGetEmailPreferencesV1.js";
import { tool$peoplePeopleControllerGetEmploymentEvidenceV1 } from "./tools/peoplePeopleControllerGetEmploymentEvidenceV1.js";
import { tool$peoplePeopleControllerGetFleetComplianceV1 } from "./tools/peoplePeopleControllerGetFleetComplianceV1.js";
import { tool$peoplePeopleControllerGetMemberAccessV1 } from "./tools/peoplePeopleControllerGetMemberAccessV1.js";
import { tool$peoplePeopleControllerGetMentionableMembersV1 } from "./tools/peoplePeopleControllerGetMentionableMembersV1.js";
import { tool$peoplePeopleControllerGetPersonByIdV1 } from "./tools/peoplePeopleControllerGetPersonByIdV1.js";
import { tool$peoplePeopleControllerGetTestStatsByAssigneeV1 } from "./tools/peoplePeopleControllerGetTestStatsByAssigneeV1.js";
import { tool$peoplePeopleControllerGetTrainingVideosV1 } from "./tools/peoplePeopleControllerGetTrainingVideosV1.js";
import { tool$peoplePeopleControllerInviteMembersV1 } from "./tools/peoplePeopleControllerInviteMembersV1.js";
import { tool$peoplePeopleControllerReactivateMemberV1 } from "./tools/peoplePeopleControllerReactivateMemberV1.js";
import { tool$peoplePeopleControllerRemoveHostV1 } from "./tools/peoplePeopleControllerRemoveHostV1.js";
import { tool$peoplePeopleControllerResendPortalInviteV1 } from "./tools/peoplePeopleControllerResendPortalInviteV1.js";
import { tool$peoplePeopleControllerUnlinkDeviceV1 } from "./tools/peoplePeopleControllerUnlinkDeviceV1.js";
import { tool$peoplePeopleControllerUpdateEmailPreferencesV1 } from "./tools/peoplePeopleControllerUpdateEmailPreferencesV1.js";
import { tool$peoplePeopleControllerUpdateMemberV1 } from "./tools/peoplePeopleControllerUpdateMemberV1.js";
import { tool$peoplePeopleControllerUploadEmploymentEvidenceV1 } from "./tools/peoplePeopleControllerUploadEmploymentEvidenceV1.js";
import { tool$policiesPoliciesControllerAcceptPolicyChangesV1 } from "./tools/policiesPoliciesControllerAcceptPolicyChangesV1.js";
import { tool$policiesPoliciesControllerAddPolicyControlsV1 } from "./tools/policiesPoliciesControllerAddPolicyControlsV1.js";
import { tool$policiesPoliciesControllerAiChatPolicyV1 } from "./tools/policiesPoliciesControllerAiChatPolicyV1.js";
import { tool$policiesPoliciesControllerConfirmPolicyPdfUploadedV1 } from "./tools/policiesPoliciesControllerConfirmPolicyPdfUploadedV1.js";
import { tool$policiesPoliciesControllerCreatePolicyV1 } from "./tools/policiesPoliciesControllerCreatePolicyV1.js";
import { tool$policiesPoliciesControllerCreatePolicyVersionV1 } from "./tools/policiesPoliciesControllerCreatePolicyVersionV1.js";
import { tool$policiesPoliciesControllerDeletePolicyPdfV1 } from "./tools/policiesPoliciesControllerDeletePolicyPdfV1.js";
import { tool$policiesPoliciesControllerDeletePolicyV1 } from "./tools/policiesPoliciesControllerDeletePolicyV1.js";
import { tool$policiesPoliciesControllerDeletePolicyVersionV1 } from "./tools/policiesPoliciesControllerDeletePolicyVersionV1.js";
import { tool$policiesPoliciesControllerDenyPolicyChangesV1 } from "./tools/policiesPoliciesControllerDenyPolicyChangesV1.js";
import { tool$policiesPoliciesControllerDownloadAllPoliciesV1 } from "./tools/policiesPoliciesControllerDownloadAllPoliciesV1.js";
import { tool$policiesPoliciesControllerGetAllPoliciesV1 } from "./tools/policiesPoliciesControllerGetAllPoliciesV1.js";
import { tool$policiesPoliciesControllerGetPdfSignedUrlV1 } from "./tools/policiesPoliciesControllerGetPdfSignedUrlV1.js";
import { tool$policiesPoliciesControllerGetPdfUrlV1 } from "./tools/policiesPoliciesControllerGetPdfUrlV1.js";
import { tool$policiesPoliciesControllerGetPolicyControlsV1 } from "./tools/policiesPoliciesControllerGetPolicyControlsV1.js";
import { tool$policiesPoliciesControllerGetPolicyEvidenceTasksV1 } from "./tools/policiesPoliciesControllerGetPolicyEvidenceTasksV1.js";
import { tool$policiesPoliciesControllerGetPolicyV1 } from "./tools/policiesPoliciesControllerGetPolicyV1.js";
import { tool$policiesPoliciesControllerGetPolicyVersionByIdV1 } from "./tools/policiesPoliciesControllerGetPolicyVersionByIdV1.js";
import { tool$policiesPoliciesControllerGetPolicyVersionsV1 } from "./tools/policiesPoliciesControllerGetPolicyVersionsV1.js";
import { tool$policiesPoliciesControllerPublishAllPoliciesV1 } from "./tools/policiesPoliciesControllerPublishAllPoliciesV1.js";
import { tool$policiesPoliciesControllerPublishPolicyVersionV1 } from "./tools/policiesPoliciesControllerPublishPolicyVersionV1.js";
import { tool$policiesPoliciesControllerRegeneratePolicyV1 } from "./tools/policiesPoliciesControllerRegeneratePolicyV1.js";
import { tool$policiesPoliciesControllerRemovePolicyControlV1 } from "./tools/policiesPoliciesControllerRemovePolicyControlV1.js";
import { tool$policiesPoliciesControllerRequestPolicyPdfUploadUrlV1 } from "./tools/policiesPoliciesControllerRequestPolicyPdfUploadUrlV1.js";
import { tool$policiesPoliciesControllerSetActivePolicyVersionV1 } from "./tools/policiesPoliciesControllerSetActivePolicyVersionV1.js";
import { tool$policiesPoliciesControllerSubmitVersionForApprovalV1 } from "./tools/policiesPoliciesControllerSubmitVersionForApprovalV1.js";
import { tool$policiesPoliciesControllerUpdatePolicyV1 } from "./tools/policiesPoliciesControllerUpdatePolicyV1.js";
import { tool$policiesPoliciesControllerUpdateVersionContentV1 } from "./tools/policiesPoliciesControllerUpdateVersionContentV1.js";
import { tool$questionnaireQuestionnaireControllerAnswerSingleQuestionV1 } from "./tools/questionnaireQuestionnaireControllerAnswerSingleQuestionV1.js";
import { tool$questionnaireQuestionnaireControllerDeleteAnswerV1 } from "./tools/questionnaireQuestionnaireControllerDeleteAnswerV1.js";
import { tool$questionnaireQuestionnaireControllerDeleteByIdV1 } from "./tools/questionnaireQuestionnaireControllerDeleteByIdV1.js";
import { tool$questionnaireQuestionnaireControllerExportByIdV1 } from "./tools/questionnaireQuestionnaireControllerExportByIdV1.js";
import { tool$questionnaireQuestionnaireControllerFindAllV1 } from "./tools/questionnaireQuestionnaireControllerFindAllV1.js";
import { tool$questionnaireQuestionnaireControllerFindByIdV1 } from "./tools/questionnaireQuestionnaireControllerFindByIdV1.js";
import { tool$questionnaireQuestionnaireControllerParseQuestionnaireV1 } from "./tools/questionnaireQuestionnaireControllerParseQuestionnaireV1.js";
import { tool$questionnaireQuestionnaireControllerSaveAnswerV1 } from "./tools/questionnaireQuestionnaireControllerSaveAnswerV1.js";
import { tool$questionnaireQuestionnaireControllerTriggerAutoAnswerV1 } from "./tools/questionnaireQuestionnaireControllerTriggerAutoAnswerV1.js";
import { tool$questionnaireQuestionnaireControllerUploadAndParseV1 } from "./tools/questionnaireQuestionnaireControllerUploadAndParseV1.js";
import { tool$risksRisksControllerCreateRiskV1 } from "./tools/risksRisksControllerCreateRiskV1.js";
import { tool$risksRisksControllerDeleteRiskV1 } from "./tools/risksRisksControllerDeleteRiskV1.js";
import { tool$risksRisksControllerGetAllRisksV1 } from "./tools/risksRisksControllerGetAllRisksV1.js";
import { tool$risksRisksControllerGetRiskByIdV1 } from "./tools/risksRisksControllerGetRiskByIdV1.js";
import { tool$risksRisksControllerGetStatsByAssigneeV1 } from "./tools/risksRisksControllerGetStatsByAssigneeV1.js";
import { tool$risksRisksControllerGetStatsByDepartmentV1 } from "./tools/risksRisksControllerGetStatsByDepartmentV1.js";
import { tool$risksRisksControllerUpdateRiskV1 } from "./tools/risksRisksControllerUpdateRiskV1.js";
import { tool$rolesRolesControllerCreateRoleV1 } from "./tools/rolesRolesControllerCreateRoleV1.js";
import { tool$rolesRolesControllerDeleteRoleV1 } from "./tools/rolesRolesControllerDeleteRoleV1.js";
import { tool$rolesRolesControllerGetBuiltInObligationsV1 } from "./tools/rolesRolesControllerGetBuiltInObligationsV1.js";
import { tool$rolesRolesControllerGetPermissionsForRolesV1 } from "./tools/rolesRolesControllerGetPermissionsForRolesV1.js";
import { tool$rolesRolesControllerGetRoleV1 } from "./tools/rolesRolesControllerGetRoleV1.js";
import { tool$rolesRolesControllerListRolesV1 } from "./tools/rolesRolesControllerListRolesV1.js";
import { tool$rolesRolesControllerUpdateBuiltInObligationsV1 } from "./tools/rolesRolesControllerUpdateBuiltInObligationsV1.js";
import { tool$rolesRolesControllerUpdateRoleV1 } from "./tools/rolesRolesControllerUpdateRoleV1.js";
import { tool$securityPenetrationTestsPentestFindingContextsControllerListV1 } from "./tools/securityPenetrationTestsPentestFindingContextsControllerListV1.js";
import { tool$securityPenetrationTestsPentestFindingContextsControllerRemoveV1 } from "./tools/securityPenetrationTestsPentestFindingContextsControllerRemoveV1.js";
import { tool$securityPenetrationTestsPentestFindingContextsControllerUpsertV1 } from "./tools/securityPenetrationTestsPentestFindingContextsControllerUpsertV1.js";
import { tool$securityPenetrationTestsSecurityPenetrationTestsControllerCreateV1 } from "./tools/securityPenetrationTestsSecurityPenetrationTestsControllerCreateV1.js";
import { tool$securityPenetrationTestsSecurityPenetrationTestsControllerGetByIdV1 } from "./tools/securityPenetrationTestsSecurityPenetrationTestsControllerGetByIdV1.js";
import { tool$securityPenetrationTestsSecurityPenetrationTestsControllerGetEventsV1 } from "./tools/securityPenetrationTestsSecurityPenetrationTestsControllerGetEventsV1.js";
import { tool$securityPenetrationTestsSecurityPenetrationTestsControllerGetIssuesV1 } from "./tools/securityPenetrationTestsSecurityPenetrationTestsControllerGetIssuesV1.js";
import { tool$securityPenetrationTestsSecurityPenetrationTestsControllerGetPdfV1 } from "./tools/securityPenetrationTestsSecurityPenetrationTestsControllerGetPdfV1.js";
import { tool$securityPenetrationTestsSecurityPenetrationTestsControllerGetProgressV1 } from "./tools/securityPenetrationTestsSecurityPenetrationTestsControllerGetProgressV1.js";
import { tool$securityPenetrationTestsSecurityPenetrationTestsControllerGetReportV1 } from "./tools/securityPenetrationTestsSecurityPenetrationTestsControllerGetReportV1.js";
import { tool$securityPenetrationTestsSecurityPenetrationTestsControllerListV1 } from "./tools/securityPenetrationTestsSecurityPenetrationTestsControllerListV1.js";
import { tool$soaSOAControllerApproveDocumentV1 } from "./tools/soaSOAControllerApproveDocumentV1.js";
import { tool$soaSOAControllerAutoFillV1 } from "./tools/soaSOAControllerAutoFillV1.js";
import { tool$soaSOAControllerCreateDocumentV1 } from "./tools/soaSOAControllerCreateDocumentV1.js";
import { tool$soaSOAControllerDeclineDocumentV1 } from "./tools/soaSOAControllerDeclineDocumentV1.js";
import { tool$soaSOAControllerEnsureSetupV1 } from "./tools/soaSOAControllerEnsureSetupV1.js";
import { tool$soaSOAControllerExportDocumentV1 } from "./tools/soaSOAControllerExportDocumentV1.js";
import { tool$soaSOAControllerGetSetupV1 } from "./tools/soaSOAControllerGetSetupV1.js";
import { tool$soaSOAControllerSaveAnswerV1 } from "./tools/soaSOAControllerSaveAnswerV1.js";
import { tool$soaSOAControllerSubmitForApprovalV1 } from "./tools/soaSOAControllerSubmitForApprovalV1.js";
import { tool$taskAutomationsAutomationsControllerDeleteAutomationV1 } from "./tools/taskAutomationsAutomationsControllerDeleteAutomationV1.js";
import { tool$taskAutomationsAutomationsControllerGetAutomationRunsV1 } from "./tools/taskAutomationsAutomationsControllerGetAutomationRunsV1.js";
import { tool$taskAutomationsAutomationsControllerGetAutomationV1 } from "./tools/taskAutomationsAutomationsControllerGetAutomationV1.js";
import { tool$taskAutomationsAutomationsControllerGetAutomationVersionsV1 } from "./tools/taskAutomationsAutomationsControllerGetAutomationVersionsV1.js";
import { tool$taskAutomationsAutomationsControllerGetTaskAutomationRunsV1 } from "./tools/taskAutomationsAutomationsControllerGetTaskAutomationRunsV1.js";
import { tool$taskAutomationsAutomationsControllerGetTaskAutomationsV1 } from "./tools/taskAutomationsAutomationsControllerGetTaskAutomationsV1.js";
import { tool$taskAutomationsAutomationsControllerUpdateAutomationV1 } from "./tools/taskAutomationsAutomationsControllerUpdateAutomationV1.js";
import { tool$taskManagementTaskManagementControllerCreateTaskItemV1 } from "./tools/taskManagementTaskManagementControllerCreateTaskItemV1.js";
import { tool$taskManagementTaskManagementControllerDeleteTaskItemAttachmentV1 } from "./tools/taskManagementTaskManagementControllerDeleteTaskItemAttachmentV1.js";
import { tool$taskManagementTaskManagementControllerDeleteTaskItemV1 } from "./tools/taskManagementTaskManagementControllerDeleteTaskItemV1.js";
import { tool$taskManagementTaskManagementControllerGetTaskItemActivityV1 } from "./tools/taskManagementTaskManagementControllerGetTaskItemActivityV1.js";
import { tool$taskManagementTaskManagementControllerGetTaskItemsStatsV1 } from "./tools/taskManagementTaskManagementControllerGetTaskItemsStatsV1.js";
import { tool$taskManagementTaskManagementControllerGetTaskItemsV1 } from "./tools/taskManagementTaskManagementControllerGetTaskItemsV1.js";
import { tool$taskManagementTaskManagementControllerUpdateTaskItemV1 } from "./tools/taskManagementTaskManagementControllerUpdateTaskItemV1.js";
import { tool$taskManagementTaskManagementControllerUploadTaskItemAttachmentV1 } from "./tools/taskManagementTaskManagementControllerUploadTaskItemAttachmentV1.js";
import { tool$tasksTasksControllerApproveTaskV1 } from "./tools/tasksTasksControllerApproveTaskV1.js";
import { tool$tasksTasksControllerBulkSubmitForReviewV1 } from "./tools/tasksTasksControllerBulkSubmitForReviewV1.js";
import { tool$tasksTasksControllerCreateTaskV1 } from "./tools/tasksTasksControllerCreateTaskV1.js";
import { tool$tasksTasksControllerDeleteTaskAttachmentV1 } from "./tools/tasksTasksControllerDeleteTaskAttachmentV1.js";
import { tool$tasksTasksControllerDeleteTasksV1 } from "./tools/tasksTasksControllerDeleteTasksV1.js";
import { tool$tasksTasksControllerDeleteTaskV1 } from "./tools/tasksTasksControllerDeleteTaskV1.js";
import { tool$tasksTasksControllerGetTaskActivityV1 } from "./tools/tasksTasksControllerGetTaskActivityV1.js";
import { tool$tasksTasksControllerGetTaskAttachmentDownloadUrlV1 } from "./tools/tasksTasksControllerGetTaskAttachmentDownloadUrlV1.js";
import { tool$tasksTasksControllerGetTaskAttachmentsV1 } from "./tools/tasksTasksControllerGetTaskAttachmentsV1.js";
import { tool$tasksTasksControllerGetTaskOptionsV1 } from "./tools/tasksTasksControllerGetTaskOptionsV1.js";
import { tool$tasksTasksControllerGetTaskPoliciesV1 } from "./tools/tasksTasksControllerGetTaskPoliciesV1.js";
import { tool$tasksTasksControllerGetTasksV1 } from "./tools/tasksTasksControllerGetTasksV1.js";
import { tool$tasksTasksControllerGetTaskTemplatesV1 } from "./tools/tasksTasksControllerGetTaskTemplatesV1.js";
import { tool$tasksTasksControllerGetTaskV1 } from "./tools/tasksTasksControllerGetTaskV1.js";
import { tool$tasksTasksControllerRegenerateTaskV1 } from "./tools/tasksTasksControllerRegenerateTaskV1.js";
import { tool$tasksTasksControllerRejectTaskV1 } from "./tools/tasksTasksControllerRejectTaskV1.js";
import { tool$tasksTasksControllerReorderTasksV1 } from "./tools/tasksTasksControllerReorderTasksV1.js";
import { tool$tasksTasksControllerSubmitForReviewV1 } from "./tools/tasksTasksControllerSubmitForReviewV1.js";
import { tool$tasksTasksControllerUpdateTasksAssigneeV1 } from "./tools/tasksTasksControllerUpdateTasksAssigneeV1.js";
import { tool$tasksTasksControllerUpdateTasksStatusV1 } from "./tools/tasksTasksControllerUpdateTasksStatusV1.js";
import { tool$tasksTasksControllerUpdateTaskV1 } from "./tools/tasksTasksControllerUpdateTaskV1.js";
import { tool$tasksTasksControllerUploadTaskAttachmentV1 } from "./tools/tasksTasksControllerUploadTaskAttachmentV1.js";
import { tool$trainingTrainingControllerGenerateCertificateV1 } from "./tools/trainingTrainingControllerGenerateCertificateV1.js";
import { tool$trainingTrainingControllerGenerateHipaaCertificateV1 } from "./tools/trainingTrainingControllerGenerateHipaaCertificateV1.js";
import { tool$trainingTrainingControllerGetCompletionsV1 } from "./tools/trainingTrainingControllerGetCompletionsV1.js";
import { tool$trainingTrainingControllerMarkVideoCompleteV1 } from "./tools/trainingTrainingControllerMarkVideoCompleteV1.js";
import { tool$trainingTrainingControllerSendTrainingCompletionEmailV1 } from "./tools/trainingTrainingControllerSendTrainingCompletionEmailV1.js";
import { tool$trustAccessTrustAccessControllerApproveRequestV1 } from "./tools/trustAccessTrustAccessControllerApproveRequestV1.js";
import { tool$trustAccessTrustAccessControllerCreateAccessRequestV1 } from "./tools/trustAccessTrustAccessControllerCreateAccessRequestV1.js";
import { tool$trustAccessTrustAccessControllerDenyRequestV1 } from "./tools/trustAccessTrustAccessControllerDenyRequestV1.js";
import { tool$trustAccessTrustAccessControllerGetAccessRequestV1 } from "./tools/trustAccessTrustAccessControllerGetAccessRequestV1.js";
import { tool$trustAccessTrustAccessControllerGetFaqsV1 } from "./tools/trustAccessTrustAccessControllerGetFaqsV1.js";
import { tool$trustAccessTrustAccessControllerGetPublicCustomFrameworksV1 } from "./tools/trustAccessTrustAccessControllerGetPublicCustomFrameworksV1.js";
import { tool$trustAccessTrustAccessControllerGetPublicCustomLinksV1 } from "./tools/trustAccessTrustAccessControllerGetPublicCustomLinksV1.js";
import { tool$trustAccessTrustAccessControllerGetPublicFaviconV1 } from "./tools/trustAccessTrustAccessControllerGetPublicFaviconV1.js";
import { tool$trustAccessTrustAccessControllerGetPublicOverviewV1 } from "./tools/trustAccessTrustAccessControllerGetPublicOverviewV1.js";
import { tool$trustAccessTrustAccessControllerGetPublicSecurityQuestionnaireV1 } from "./tools/trustAccessTrustAccessControllerGetPublicSecurityQuestionnaireV1.js";
import { tool$trustAccessTrustAccessControllerGetPublicVendorsV1 } from "./tools/trustAccessTrustAccessControllerGetPublicVendorsV1.js";
import { tool$trustAccessTrustAccessControllerListAccessRequestsV1 } from "./tools/trustAccessTrustAccessControllerListAccessRequestsV1.js";
import { tool$trustAccessTrustAccessControllerListGrantsV1 } from "./tools/trustAccessTrustAccessControllerListGrantsV1.js";
import { tool$trustAccessTrustAccessControllerPreviewNdaV1 } from "./tools/trustAccessTrustAccessControllerPreviewNdaV1.js";
import { tool$trustAccessTrustAccessControllerReclaimAccessV1 } from "./tools/trustAccessTrustAccessControllerReclaimAccessV1.js";
import { tool$trustAccessTrustAccessControllerResendAccessEmailV1 } from "./tools/trustAccessTrustAccessControllerResendAccessEmailV1.js";
import { tool$trustAccessTrustAccessControllerResendNdaV1 } from "./tools/trustAccessTrustAccessControllerResendNdaV1.js";
import { tool$trustAccessTrustAccessControllerRevokeGrantV1 } from "./tools/trustAccessTrustAccessControllerRevokeGrantV1.js";
import { tool$trustPortalTrustPortalControllerAddCustomDomainV1 } from "./tools/trustPortalTrustPortalControllerAddCustomDomainV1.js";
import { tool$trustPortalTrustPortalControllerCheckDnsRecordsV1 } from "./tools/trustPortalTrustPortalControllerCheckDnsRecordsV1.js";
import { tool$trustPortalTrustPortalControllerCreateCustomLinkV1 } from "./tools/trustPortalTrustPortalControllerCreateCustomLinkV1.js";
import { tool$trustPortalTrustPortalControllerDeleteCustomLinkV1 } from "./tools/trustPortalTrustPortalControllerDeleteCustomLinkV1.js";
import { tool$trustPortalTrustPortalControllerDeleteTrustDocumentV1 } from "./tools/trustPortalTrustPortalControllerDeleteTrustDocumentV1.js";
import { tool$trustPortalTrustPortalControllerGetComplianceResourceUrlV1 } from "./tools/trustPortalTrustPortalControllerGetComplianceResourceUrlV1.js";
import { tool$trustPortalTrustPortalControllerGetDomainStatusV1 } from "./tools/trustPortalTrustPortalControllerGetDomainStatusV1.js";
import { tool$trustPortalTrustPortalControllerGetOverviewV1 } from "./tools/trustPortalTrustPortalControllerGetOverviewV1.js";
import { tool$trustPortalTrustPortalControllerGetSettingsV1 } from "./tools/trustPortalTrustPortalControllerGetSettingsV1.js";
import { tool$trustPortalTrustPortalControllerGetTrustDocumentUrlV1 } from "./tools/trustPortalTrustPortalControllerGetTrustDocumentUrlV1.js";
import { tool$trustPortalTrustPortalControllerListComplianceResourcesV1 } from "./tools/trustPortalTrustPortalControllerListComplianceResourcesV1.js";
import { tool$trustPortalTrustPortalControllerListCustomFrameworksV1 } from "./tools/trustPortalTrustPortalControllerListCustomFrameworksV1.js";
import { tool$trustPortalTrustPortalControllerListCustomLinksV1 } from "./tools/trustPortalTrustPortalControllerListCustomLinksV1.js";
import { tool$trustPortalTrustPortalControllerListTrustDocumentsV1 } from "./tools/trustPortalTrustPortalControllerListTrustDocumentsV1.js";
import { tool$trustPortalTrustPortalControllerListVendorsV1 } from "./tools/trustPortalTrustPortalControllerListVendorsV1.js";
import { tool$trustPortalTrustPortalControllerRemoveCustomFrameworkBadgeV1 } from "./tools/trustPortalTrustPortalControllerRemoveCustomFrameworkBadgeV1.js";
import { tool$trustPortalTrustPortalControllerRemoveFaviconV1 } from "./tools/trustPortalTrustPortalControllerRemoveFaviconV1.js";
import { tool$trustPortalTrustPortalControllerReorderCustomLinksV1 } from "./tools/trustPortalTrustPortalControllerReorderCustomLinksV1.js";
import { tool$trustPortalTrustPortalControllerTogglePortalV1 } from "./tools/trustPortalTrustPortalControllerTogglePortalV1.js";
import { tool$trustPortalTrustPortalControllerUpdateAllowedDomainsV1 } from "./tools/trustPortalTrustPortalControllerUpdateAllowedDomainsV1.js";
import { tool$trustPortalTrustPortalControllerUpdateAllowedEmailsV1 } from "./tools/trustPortalTrustPortalControllerUpdateAllowedEmailsV1.js";
import { tool$trustPortalTrustPortalControllerUpdateCustomFrameworkV1 } from "./tools/trustPortalTrustPortalControllerUpdateCustomFrameworkV1.js";
import { tool$trustPortalTrustPortalControllerUpdateCustomLinkV1 } from "./tools/trustPortalTrustPortalControllerUpdateCustomLinkV1.js";
import { tool$trustPortalTrustPortalControllerUpdateFaqsV1 } from "./tools/trustPortalTrustPortalControllerUpdateFaqsV1.js";
import { tool$trustPortalTrustPortalControllerUpdateFrameworksV1 } from "./tools/trustPortalTrustPortalControllerUpdateFrameworksV1.js";
import { tool$trustPortalTrustPortalControllerUpdateOverviewV1 } from "./tools/trustPortalTrustPortalControllerUpdateOverviewV1.js";
import { tool$trustPortalTrustPortalControllerUpdateSecurityQuestionnaireV1 } from "./tools/trustPortalTrustPortalControllerUpdateSecurityQuestionnaireV1.js";
import { tool$trustPortalTrustPortalControllerUpdateVendorTrustSettingsV1 } from "./tools/trustPortalTrustPortalControllerUpdateVendorTrustSettingsV1.js";
import { tool$trustPortalTrustPortalControllerUploadComplianceResourceV1 } from "./tools/trustPortalTrustPortalControllerUploadComplianceResourceV1.js";
import { tool$trustPortalTrustPortalControllerUploadCustomFrameworkBadgeV1 } from "./tools/trustPortalTrustPortalControllerUploadCustomFrameworkBadgeV1.js";
import { tool$trustPortalTrustPortalControllerUploadFaviconV1 } from "./tools/trustPortalTrustPortalControllerUploadFaviconV1.js";
import { tool$trustPortalTrustPortalControllerUploadTrustDocumentV1 } from "./tools/trustPortalTrustPortalControllerUploadTrustDocumentV1.js";
import { tool$uploadsUploadsControllerCreateUploadUrlV1 } from "./tools/uploadsUploadsControllerCreateUploadUrlV1.js";
import { tool$vendorsVendorsControllerCreateVendorV1 } from "./tools/vendorsVendorsControllerCreateVendorV1.js";
import { tool$vendorsVendorsControllerDeleteVendorV1 } from "./tools/vendorsVendorsControllerDeleteVendorV1.js";
import { tool$vendorsVendorsControllerGetAllVendorsV1 } from "./tools/vendorsVendorsControllerGetAllVendorsV1.js";
import { tool$vendorsVendorsControllerGetVendorByIdV1 } from "./tools/vendorsVendorsControllerGetVendorByIdV1.js";
import { tool$vendorsVendorsControllerSearchGlobalVendorsV1 } from "./tools/vendorsVendorsControllerSearchGlobalVendorsV1.js";
import { tool$vendorsVendorsControllerTriggerAssessmentV1 } from "./tools/vendorsVendorsControllerTriggerAssessmentV1.js";
import { tool$vendorsVendorsControllerUpdateVendorV1 } from "./tools/vendorsVendorsControllerUpdateVendorV1.js";

export function createMCPServer(deps: {
  logger: ConsoleLogger;
  allowedTools?: string[] | undefined;
  dynamic?: boolean | undefined;
  scopes?: MCPScope[] | undefined;
  annotationFilter?: MCPToolAnnotationFilter | undefined;
  getSDK?: () => CompAiCore;
  serverURL?: string | undefined;
  security?: SDKOptions["security"] | undefined;
  serverIdx?: SDKOptions["serverIdx"] | undefined;
}) {
  const server = new McpServer({
    name: "CompAi",
    version: "0.2.6",
  });

  const getClient = deps.getSDK || (() =>
    new CompAiCore({
      security: deps.security,
      serverURL: deps.serverURL,
      serverIdx: deps.serverIdx,
      debugLogger: deps.logger.level === "debug"
        ? {
          log: (...args) => console.log(...args),
          group: (...args) => console.group(...args),
          groupEnd: (...args) => console.groupEnd(...args),
        }
        : undefined,
    }));

  const scopes = new Set(deps.scopes);

  const allowedTools = deps.allowedTools && new Set(deps.allowedTools);
  const [tool, tools, toolMap] = createRegisterTool(
    deps.logger,
    server,
    getClient,
    scopes,
    allowedTools,
    deps.dynamic,
    deps.annotationFilter,
  );
  const resource = createRegisterResource(
    deps.logger,
    server,
    getClient,
    scopes,
  );
  const resourceTemplate = createRegisterResourceTemplate(
    deps.logger,
    server,
    getClient,
    scopes,
  );
  const prompt = createRegisterPrompt(deps.logger, server, getClient, scopes);
  const register = { tool, resource, resourceTemplate, prompt };
  void register; // suppress unused warnings

  tool(tool$organizationOrganizationControllerGetOrganizationV1);
  tool(tool$organizationOrganizationControllerUpdateOrganizationV1);
  tool(tool$organizationOrganizationControllerDeleteOrganizationV1);
  tool(tool$organizationOrganizationControllerGetOnboardingV1);
  tool(tool$organizationOrganizationControllerTransferOwnershipV1);
  tool(tool$organizationOrganizationControllerUpdateRoleNotificationsV1);
  tool(tool$organizationOrganizationControllerGetRoleNotificationsV1);
  tool(tool$organizationOrganizationControllerListApiKeysV1);
  tool(tool$organizationOrganizationControllerCreateApiKeyV1);
  tool(tool$organizationOrganizationControllerGetAvailableScopesV1);
  tool(tool$organizationOrganizationControllerGetPrimaryColorV1);
  tool(tool$organizationOrganizationControllerUploadLogoV1);
  tool(tool$organizationOrganizationControllerRemoveLogoV1);
  tool(tool$organizationOrganizationControllerRevokeApiKeyV1);
  tool(tool$organizationOrganizationAccessControllerAutoApproveV1);
  tool(tool$peoplePeopleControllerInviteMembersV1);
  tool(tool$peoplePeopleControllerGetAllPeopleV1);
  tool(tool$peoplePeopleControllerCreateMemberV1);
  tool(tool$peoplePeopleControllerGetDevicesV1);
  tool(tool$peoplePeopleControllerGetTestStatsByAssigneeV1);
  tool(tool$peoplePeopleControllerBulkCreateMembersV1);
  tool(tool$peoplePeopleControllerGetMentionableMembersV1);
  tool(tool$peoplePeopleControllerReactivateMemberV1);
  tool(tool$peoplePeopleControllerGetPersonByIdV1);
  tool(tool$peoplePeopleControllerUpdateMemberV1);
  tool(tool$peoplePeopleControllerDeleteMemberV1);
  tool(tool$peoplePeopleControllerGetMemberAccessV1);
  tool(tool$peoplePeopleControllerGetTrainingVideosV1);
  tool(tool$peoplePeopleControllerGetFleetComplianceV1);
  tool(tool$peoplePeopleControllerRemoveHostV1);
  tool(tool$peoplePeopleControllerResendPortalInviteV1);
  tool(tool$peoplePeopleControllerUnlinkDeviceV1);
  tool(tool$peoplePeopleControllerGetEmploymentEvidenceV1);
  tool(tool$peoplePeopleControllerUploadEmploymentEvidenceV1);
  tool(tool$peoplePeopleControllerDeleteEmploymentEvidenceV1);
  tool(tool$peoplePeopleControllerGetEmailPreferencesV1);
  tool(tool$peoplePeopleControllerUpdateEmailPreferencesV1);
  tool(tool$attachmentsAttachmentsControllerCreateAttachmentV1);
  tool(tool$attachmentsAttachmentsControllerGetAttachmentDownloadUrlV1);
  tool(tool$uploadsUploadsControllerCreateUploadUrlV1);
  tool(tool$integrationsConnectionsControllerListProvidersV1);
  tool(tool$integrationsConnectionsControllerGetProviderV1);
  tool(tool$integrationsConnectionsControllerListConnectionsV1);
  tool(tool$integrationsConnectionsControllerCreateConnectionV1);
  tool(tool$integrationsConnectionsControllerGetConnectionV1);
  tool(tool$integrationsConnectionsControllerDeleteConnectionV1);
  tool(tool$integrationsConnectionsControllerUpdateConnectionV1);
  tool(tool$integrationsConnectionsControllerTestConnectionV1);
  tool(tool$integrationsConnectionsControllerPauseConnectionV1);
  tool(tool$integrationsConnectionsControllerResumeConnectionV1);
  tool(tool$integrationsConnectionsControllerDisconnectConnectionV1);
  tool(tool$integrationsConnectionsControllerUpdateConnectionServicesV1);
  tool(tool$integrationsServicesControllerGetConnectionServicesV1);
  tool(tool$integrationsChecksControllerListProviderChecksV1);
  tool(tool$integrationsChecksControllerListConnectionChecksV1);
  tool(tool$integrationsChecksControllerRunConnectionChecksV1);
  tool(tool$integrationsChecksControllerRunSingleCheckV1);
  tool(tool$integrationsVariablesControllerGetProviderVariablesV1);
  tool(tool$integrationsVariablesControllerGetConnectionVariablesV1);
  tool(tool$integrationsVariablesControllerSaveConnectionVariablesV1);
  tool(tool$integrationsVariablesControllerFetchVariableOptionsV1);
  tool(tool$integrationsTaskIntegrationsControllerGetChecksForTaskTemplateV1);
  tool(tool$integrationsTaskIntegrationsControllerGetChecksForTaskV1);
  tool(tool$integrationsTaskIntegrationsControllerRunCheckForTaskV1);
  tool(tool$integrationsTaskIntegrationsControllerDisconnectCheckFromTaskV1);
  tool(tool$integrationsTaskIntegrationsControllerReconnectCheckToTaskV1);
  tool(tool$integrationsTaskIntegrationsControllerGetTaskCheckRunsV1);
  tool(tool$integrationsSyncControllerSyncGoogleWorkspaceEmployeesV1);
  tool(tool$integrationsSyncControllerGetGoogleWorkspaceStatusV1);
  tool(tool$integrationsSyncControllerSyncRipplingEmployeesV1);
  tool(tool$integrationsSyncControllerGetRipplingStatusV1);
  tool(tool$integrationsSyncControllerSyncJumpCloudEmployeesV1);
  tool(tool$integrationsSyncControllerGetJumpCloudStatusV1);
  tool(tool$integrationsSyncControllerGetEmployeeSyncProviderV1);
  tool(tool$integrationsSyncControllerSetEmployeeSyncProviderV1);
  tool(tool$integrationsSyncControllerGetDeviceSyncProviderV1);
  tool(tool$integrationsSyncControllerSetDeviceSyncProviderV1);
  tool(tool$integrationsSyncControllerGetAvailableSyncProvidersV1);
  tool(tool$integrationsSyncControllerSyncDynamicProviderEmployeesV1);
  tool(tool$integrationsSyncControllerSyncDynamicProviderDevicesV1);
  tool(tool$integrationsTwoFactorSourceControllerGetTwoFactorSourceV1);
  tool(tool$integrationsTwoFactorSourceControllerSetTwoFactorSourceV1);
  tool(
    tool$integrationsTwoFactorSourceControllerGetAvailableTwoFactorSourcesV1,
  );
  tool(tool$integrationsTwoFactorSourceControllerGetTwoFactorStatusesV1);
  tool(tool$cloudSecurityCloudSecurityControllerGetActivityV1);
  tool(tool$cloudSecurityCloudSecurityControllerGetProvidersV1);
  tool(tool$cloudSecurityCloudSecurityControllerGetFindingsV1);
  tool(tool$cloudSecurityCloudSecurityControllerMarkFindingAsExceptionV1);
  tool(tool$cloudSecurityCloudSecurityControllerUpdateAwsScanModeV1);
  tool(tool$cloudSecurityCloudSecurityControllerRevokeExceptionV1);
  tool(tool$cloudSecurityCloudSecurityControllerGetHistoryV1);
  tool(tool$cloudSecurityCloudSecurityControllerGetCheckDefinitionV1);
  tool(tool$cloudSecurityCloudSecurityControllerResolveSessionV1);
  tool(tool$cloudSecurityCloudSecurityControllerScanV1);
  tool(tool$cloudSecurityCloudSecurityControllerDetectServicesV1);
  tool(tool$cloudSecurityCloudSecurityControllerDetectGcpOrgV1);
  tool(tool$cloudSecurityCloudSecurityControllerSelectGcpProjectsV1);
  tool(tool$cloudSecurityCloudSecurityControllerSetupGcpV1);
  tool(tool$cloudSecurityCloudSecurityControllerResolveGcpSetupStepV1);
  tool(tool$cloudSecurityCloudSecurityControllerSetupAzureV1);
  tool(tool$cloudSecurityCloudSecurityControllerValidateAzureV1);
  tool(tool$cloudSecurityCloudSecurityControllerTriggerScanV1);
  tool(tool$cloudSecurityCloudSecurityControllerGetRunStatusV1);
  tool(tool$risksRisksControllerGetAllRisksV1);
  tool(tool$risksRisksControllerCreateRiskV1);
  tool(tool$risksRisksControllerGetStatsByAssigneeV1);
  tool(tool$risksRisksControllerGetStatsByDepartmentV1);
  tool(tool$risksRisksControllerGetRiskByIdV1);
  tool(tool$risksRisksControllerUpdateRiskV1);
  tool(tool$risksRisksControllerDeleteRiskV1);
  tool(tool$vendorsVendorsControllerSearchGlobalVendorsV1);
  tool(tool$vendorsVendorsControllerGetAllVendorsV1);
  tool(tool$vendorsVendorsControllerCreateVendorV1);
  tool(tool$vendorsVendorsControllerGetVendorByIdV1);
  tool(tool$vendorsVendorsControllerUpdateVendorV1);
  tool(tool$vendorsVendorsControllerDeleteVendorV1);
  tool(tool$vendorsVendorsControllerTriggerAssessmentV1);
  tool(tool$contextContextControllerGetAllContextV1);
  tool(tool$contextContextControllerCreateContextV1);
  tool(tool$contextContextControllerGetContextByIdV1);
  tool(tool$contextContextControllerUpdateContextV1);
  tool(tool$contextContextControllerDeleteContextV1);
  tool(tool$devicesDevicesControllerGetAllDevicesV1);
  tool(tool$devicesDevicesControllerGetDevicesByMemberV1);
  tool(tool$devicesDevicesControllerDeleteDeviceV1);
  tool(tool$policiesPoliciesControllerGetAllPoliciesV1);
  tool(tool$policiesPoliciesControllerCreatePolicyV1);
  tool(tool$policiesPoliciesControllerPublishAllPoliciesV1);
  tool(tool$policiesPoliciesControllerDownloadAllPoliciesV1);
  tool(tool$policiesPoliciesControllerGetPolicyControlsV1);
  tool(tool$policiesPoliciesControllerAddPolicyControlsV1);
  tool(tool$policiesPoliciesControllerGetPolicyEvidenceTasksV1);
  tool(tool$policiesPoliciesControllerRegeneratePolicyV1);
  tool(tool$policiesPoliciesControllerGetPdfSignedUrlV1);
  tool(tool$policiesPoliciesControllerDeletePolicyPdfV1);
  tool(tool$policiesPoliciesControllerRequestPolicyPdfUploadUrlV1);
  tool(tool$policiesPoliciesControllerConfirmPolicyPdfUploadedV1);
  tool(tool$policiesPoliciesControllerGetPdfUrlV1);
  tool(tool$policiesPoliciesControllerRemovePolicyControlV1);
  tool(tool$policiesPoliciesControllerGetPolicyV1);
  tool(tool$policiesPoliciesControllerUpdatePolicyV1);
  tool(tool$policiesPoliciesControllerDeletePolicyV1);
  tool(tool$policiesPoliciesControllerGetPolicyVersionsV1);
  tool(tool$policiesPoliciesControllerCreatePolicyVersionV1);
  tool(tool$policiesPoliciesControllerGetPolicyVersionByIdV1);
  tool(tool$policiesPoliciesControllerUpdateVersionContentV1);
  tool(tool$policiesPoliciesControllerDeletePolicyVersionV1);
  tool(tool$policiesPoliciesControllerPublishPolicyVersionV1);
  tool(tool$policiesPoliciesControllerSetActivePolicyVersionV1);
  tool(tool$policiesPoliciesControllerSubmitVersionForApprovalV1);
  tool(tool$policiesPoliciesControllerAcceptPolicyChangesV1);
  tool(tool$policiesPoliciesControllerDenyPolicyChangesV1);
  tool(tool$policiesPoliciesControllerAiChatPolicyV1);
  tool(tool$deviceAgentDeviceAgentControllerExchangeCodeV1);
  tool(tool$deviceAgentDeviceAgentControllerGetUpdateFileV1);
  tool(tool$deviceAgentDeviceAgentControllerHeadUpdateFileV1);
  tool(tool$deviceAgentDeviceAgentControllerGenerateAuthCodeV1);
  tool(tool$deviceAgentDeviceAgentControllerGetMyOrganizationsV1);
  tool(tool$deviceAgentDeviceAgentControllerRegisterDeviceV1);
  tool(tool$deviceAgentDeviceAgentControllerCheckInV1);
  tool(tool$deviceAgentDeviceAgentControllerGetDeviceStatusV1);
  tool(tool$deviceAgentDeviceAgentControllerDownloadMacAgentV1);
  tool(tool$deviceAgentDeviceAgentControllerDownloadWindowsAgentV1);
  tool(tool$deviceAgentDeviceAgentControllerRevokeAgentAccessV1);
  tool(tool$tasksTasksControllerGetTasksV1);
  tool(tool$tasksTasksControllerCreateTaskV1);
  tool(tool$tasksTasksControllerGetTaskTemplatesV1);
  tool(tool$tasksTasksControllerUpdateTasksStatusV1);
  tool(tool$tasksTasksControllerDeleteTasksV1);
  tool(tool$tasksTasksControllerUpdateTasksAssigneeV1);
  tool(tool$tasksTasksControllerReorderTasksV1);
  tool(tool$tasksTasksControllerBulkSubmitForReviewV1);
  tool(tool$tasksTasksControllerGetTaskOptionsV1);
  tool(tool$tasksTasksControllerGetTaskV1);
  tool(tool$tasksTasksControllerUpdateTaskV1);
  tool(tool$tasksTasksControllerDeleteTaskV1);
  tool(tool$tasksTasksControllerGetTaskPoliciesV1);
  tool(tool$tasksTasksControllerGetTaskActivityV1);
  tool(tool$tasksTasksControllerRegenerateTaskV1);
  tool(tool$tasksTasksControllerSubmitForReviewV1);
  tool(tool$tasksTasksControllerApproveTaskV1);
  tool(tool$tasksTasksControllerRejectTaskV1);
  tool(tool$tasksTasksControllerGetTaskAttachmentsV1);
  tool(tool$tasksTasksControllerUploadTaskAttachmentV1);
  tool(tool$tasksTasksControllerGetTaskAttachmentDownloadUrlV1);
  tool(tool$tasksTasksControllerDeleteTaskAttachmentV1);
  tool(tool$taskAutomationsAutomationsControllerGetTaskAutomationsV1);
  tool(tool$taskAutomationsAutomationsControllerGetAutomationV1);
  tool(tool$taskAutomationsAutomationsControllerUpdateAutomationV1);
  tool(tool$taskAutomationsAutomationsControllerDeleteAutomationV1);
  tool(tool$taskAutomationsAutomationsControllerGetAutomationRunsV1);
  tool(tool$taskAutomationsAutomationsControllerGetAutomationVersionsV1);
  tool(tool$taskAutomationsAutomationsControllerGetTaskAutomationRunsV1);
  tool(tool$evidenceExportEvidenceExportControllerGetTaskEvidenceSummaryV1);
  tool(tool$evidenceExportEvidenceExportControllerExportAutomationPDFV1);
  tool(tool$evidenceExportEvidenceExportControllerExportTaskEvidenceZipV1);
  tool(
    tool$evidenceExportAuditorAuditorEvidenceExportControllerExportAllEvidenceV1,
  );
  tool(tool$commentsCommentsControllerGetCommentsV1);
  tool(tool$commentsCommentsControllerCreateCommentV1);
  tool(tool$commentsCommentsControllerUpdateCommentV1);
  tool(tool$commentsCommentsControllerDeleteCommentV1);
  tool(tool$trustPortalTrustPortalControllerGetSettingsV1);
  tool(tool$trustPortalTrustPortalControllerUploadFaviconV1);
  tool(tool$trustPortalTrustPortalControllerRemoveFaviconV1);
  tool(tool$trustPortalTrustPortalControllerGetDomainStatusV1);
  tool(tool$trustPortalTrustPortalControllerUploadComplianceResourceV1);
  tool(tool$trustPortalTrustPortalControllerGetComplianceResourceUrlV1);
  tool(tool$trustPortalTrustPortalControllerListComplianceResourcesV1);
  tool(tool$trustPortalTrustPortalControllerUploadTrustDocumentV1);
  tool(tool$trustPortalTrustPortalControllerListTrustDocumentsV1);
  tool(tool$trustPortalTrustPortalControllerGetTrustDocumentUrlV1);
  tool(tool$trustPortalTrustPortalControllerDeleteTrustDocumentV1);
  tool(tool$trustPortalTrustPortalControllerTogglePortalV1);
  tool(tool$trustPortalTrustPortalControllerAddCustomDomainV1);
  tool(tool$trustPortalTrustPortalControllerCheckDnsRecordsV1);
  tool(tool$trustPortalTrustPortalControllerUpdateFaqsV1);
  tool(tool$trustPortalTrustPortalControllerUpdateAllowedDomainsV1);
  tool(tool$trustPortalTrustPortalControllerUpdateAllowedEmailsV1);
  tool(tool$trustPortalTrustPortalControllerUpdateFrameworksV1);
  tool(tool$trustPortalTrustPortalControllerUpdateSecurityQuestionnaireV1);
  tool(tool$trustPortalTrustPortalControllerListCustomFrameworksV1);
  tool(tool$trustPortalTrustPortalControllerUpdateCustomFrameworkV1);
  tool(tool$trustPortalTrustPortalControllerUploadCustomFrameworkBadgeV1);
  tool(tool$trustPortalTrustPortalControllerRemoveCustomFrameworkBadgeV1);
  tool(tool$trustPortalTrustPortalControllerUpdateOverviewV1);
  tool(tool$trustPortalTrustPortalControllerGetOverviewV1);
  tool(tool$trustPortalTrustPortalControllerCreateCustomLinkV1);
  tool(tool$trustPortalTrustPortalControllerListCustomLinksV1);
  tool(tool$trustPortalTrustPortalControllerUpdateCustomLinkV1);
  tool(tool$trustPortalTrustPortalControllerDeleteCustomLinkV1);
  tool(tool$trustPortalTrustPortalControllerReorderCustomLinksV1);
  tool(tool$trustPortalTrustPortalControllerUpdateVendorTrustSettingsV1);
  tool(tool$trustPortalTrustPortalControllerListVendorsV1);
  tool(tool$trustAccessTrustAccessControllerCreateAccessRequestV1);
  tool(tool$trustAccessTrustAccessControllerListAccessRequestsV1);
  tool(tool$trustAccessTrustAccessControllerGetAccessRequestV1);
  tool(tool$trustAccessTrustAccessControllerApproveRequestV1);
  tool(tool$trustAccessTrustAccessControllerDenyRequestV1);
  tool(tool$trustAccessTrustAccessControllerListGrantsV1);
  tool(tool$trustAccessTrustAccessControllerRevokeGrantV1);
  tool(tool$trustAccessTrustAccessControllerResendAccessEmailV1);
  tool(tool$trustAccessTrustAccessControllerResendNdaV1);
  tool(tool$trustAccessTrustAccessControllerPreviewNdaV1);
  tool(tool$trustAccessTrustAccessControllerReclaimAccessV1);
  tool(tool$trustAccessTrustAccessControllerGetFaqsV1);
  tool(tool$trustAccessTrustAccessControllerGetPublicOverviewV1);
  tool(tool$trustAccessTrustAccessControllerGetPublicSecurityQuestionnaireV1);
  tool(tool$trustAccessTrustAccessControllerGetPublicCustomLinksV1);
  tool(tool$trustAccessTrustAccessControllerGetPublicFaviconV1);
  tool(tool$trustAccessTrustAccessControllerGetPublicVendorsV1);
  tool(tool$trustAccessTrustAccessControllerGetPublicCustomFrameworksV1);
  tool(tool$findingsFindingsControllerListFindingsV1);
  tool(tool$findingsFindingsControllerCreateFindingV1);
  tool(tool$findingsFindingsControllerGetOrganizationFindingsV1);
  tool(tool$findingsFindingsControllerGetFindingByIdV1);
  tool(tool$findingsFindingsControllerUpdateFindingV1);
  tool(tool$findingsFindingsControllerDeleteFindingV1);
  tool(tool$findingsFindingsControllerGetFindingHistoryV1);
  tool(tool$rolesRolesControllerCreateRoleV1);
  tool(tool$rolesRolesControllerListRolesV1);
  tool(tool$rolesRolesControllerGetPermissionsForRolesV1);
  tool(tool$rolesRolesControllerGetBuiltInObligationsV1);
  tool(tool$rolesRolesControllerUpdateBuiltInObligationsV1);
  tool(tool$rolesRolesControllerGetRoleV1);
  tool(tool$rolesRolesControllerUpdateRoleV1);
  tool(tool$rolesRolesControllerDeleteRoleV1);
  tool(tool$questionnaireQuestionnaireControllerFindAllV1);
  tool(tool$questionnaireQuestionnaireControllerFindByIdV1);
  tool(tool$questionnaireQuestionnaireControllerDeleteByIdV1);
  tool(tool$questionnaireQuestionnaireControllerTriggerAutoAnswerV1);
  tool(tool$questionnaireQuestionnaireControllerParseQuestionnaireV1);
  tool(tool$questionnaireQuestionnaireControllerAnswerSingleQuestionV1);
  tool(tool$questionnaireQuestionnaireControllerSaveAnswerV1);
  tool(tool$questionnaireQuestionnaireControllerDeleteAnswerV1);
  tool(tool$questionnaireQuestionnaireControllerExportByIdV1);
  tool(tool$questionnaireQuestionnaireControllerUploadAndParseV1);
  tool(tool$knowledgeBaseKnowledgeBaseControllerListDocumentsV1);
  tool(tool$knowledgeBaseKnowledgeBaseControllerListManualAnswersV1);
  tool(tool$knowledgeBaseKnowledgeBaseControllerSaveManualAnswerV1);
  tool(tool$knowledgeBaseKnowledgeBaseControllerUploadDocumentV1);
  tool(tool$knowledgeBaseKnowledgeBaseControllerGetDownloadUrlV1);
  tool(tool$knowledgeBaseKnowledgeBaseControllerGetViewUrlV1);
  tool(tool$knowledgeBaseKnowledgeBaseControllerDeleteDocumentV1);
  tool(tool$knowledgeBaseKnowledgeBaseControllerProcessDocumentsV1);
  tool(tool$knowledgeBaseKnowledgeBaseControllerCreateRunTokenV1);
  tool(tool$knowledgeBaseKnowledgeBaseControllerDeleteManualAnswerV1);
  tool(tool$knowledgeBaseKnowledgeBaseControllerDeleteAllManualAnswersV1);
  tool(tool$soaSOAControllerSaveAnswerV1);
  tool(tool$soaSOAControllerAutoFillV1);
  tool(tool$soaSOAControllerCreateDocumentV1);
  tool(tool$soaSOAControllerEnsureSetupV1);
  tool(tool$soaSOAControllerGetSetupV1);
  tool(tool$soaSOAControllerApproveDocumentV1);
  tool(tool$soaSOAControllerDeclineDocumentV1);
  tool(tool$soaSOAControllerSubmitForApprovalV1);
  tool(tool$soaSOAControllerExportDocumentV1);
  tool(tool$ismsISMSControllerEnsureSetupV1);
  tool(tool$ismsISMSControllerGetDocumentV1);
  tool(tool$ismsISMSControllerAddControlsV1);
  tool(tool$ismsISMSControllerRemoveControlV1);
  tool(tool$ismsISMSControllerGenerateV1);
  tool(tool$ismsISMSControllerSubmitForApprovalV1);
  tool(tool$ismsISMSControllerApproveV1);
  tool(tool$ismsISMSControllerDeclineV1);
  tool(tool$ismsISMSControllerDriftV1);
  tool(tool$ismsISMSControllerGetVersionsV1);
  tool(tool$ismsISMSControllerExportDocumentV1);
  tool(tool$ismsISMSRegistersControllerCreateRowV1);
  tool(tool$ismsISMSRegistersControllerUpdateRowV1);
  tool(tool$ismsISMSRegistersControllerDeleteRowV1);
  tool(tool$ismsISMSRegistersControllerBulkCreateMeasurementsV1);
  tool(tool$ismsISMSRegistersControllerSaveNarrativeV1);
  tool(tool$ismsISMSProfileControllerGetProfileV1);
  tool(tool$ismsISMSProfileControllerSaveProfileV1);
  tool(tool$ismsISMSProfileControllerGenerateAllV1);
  tool(tool$taskManagementTaskManagementControllerGetTaskItemsStatsV1);
  tool(tool$taskManagementTaskManagementControllerGetTaskItemsV1);
  tool(tool$taskManagementTaskManagementControllerCreateTaskItemV1);
  tool(tool$taskManagementTaskManagementControllerUpdateTaskItemV1);
  tool(tool$taskManagementTaskManagementControllerDeleteTaskItemV1);
  tool(tool$taskManagementTaskManagementControllerUploadTaskItemAttachmentV1);
  tool(tool$taskManagementTaskManagementControllerDeleteTaskItemAttachmentV1);
  tool(tool$taskManagementTaskManagementControllerGetTaskItemActivityV1);
  tool(tool$trainingTrainingControllerGetCompletionsV1);
  tool(tool$trainingTrainingControllerMarkVideoCompleteV1);
  tool(tool$trainingTrainingControllerSendTrainingCompletionEmailV1);
  tool(tool$trainingTrainingControllerGenerateCertificateV1);
  tool(tool$trainingTrainingControllerGenerateHipaaCertificateV1);
  tool(tool$orgChartOrgChartControllerGetOrgChartV1);
  tool(tool$orgChartOrgChartControllerUpsertOrgChartV1);
  tool(tool$orgChartOrgChartControllerDeleteOrgChartV1);
  tool(tool$orgChartOrgChartControllerUploadOrgChartV1);
  tool(tool$evidenceFormsEvidenceFormsControllerListFormsV1);
  tool(tool$evidenceFormsEvidenceFormsControllerGetFormStatusesV1);
  tool(tool$evidenceFormsEvidenceFormsControllerGetFormSettingsV1);
  tool(tool$evidenceFormsEvidenceFormsControllerUpdateFormSettingV1);
  tool(tool$evidenceFormsEvidenceFormsControllerGetMySubmissionsV1);
  tool(tool$evidenceFormsEvidenceFormsControllerGetPendingSubmissionCountV1);
  tool(tool$evidenceFormsEvidenceFormsControllerGetFormWithSubmissionsV1);
  tool(tool$evidenceFormsEvidenceFormsControllerGetSubmissionV1);
  tool(tool$evidenceFormsEvidenceFormsControllerDeleteSubmissionV1);
  tool(tool$evidenceFormsEvidenceFormsControllerSubmitFormV1);
  tool(tool$evidenceFormsEvidenceFormsControllerUploadSubmissionV1);
  tool(tool$evidenceFormsEvidenceFormsControllerReviewSubmissionV1);
  tool(tool$evidenceFormsEvidenceFormsControllerUploadFileV1);
  tool(tool$evidenceFormsEvidenceFormsControllerExportCsvV1);
  tool(tool$auditLogsAuditLogControllerGetAuditLogsV1);
  tool(tool$securityPenetrationTestsSecurityPenetrationTestsControllerListV1);
  tool(tool$securityPenetrationTestsSecurityPenetrationTestsControllerCreateV1);
  tool(
    tool$securityPenetrationTestsSecurityPenetrationTestsControllerGetByIdV1,
  );
  tool(
    tool$securityPenetrationTestsSecurityPenetrationTestsControllerGetProgressV1,
  );
  tool(
    tool$securityPenetrationTestsSecurityPenetrationTestsControllerGetIssuesV1,
  );
  tool(
    tool$securityPenetrationTestsSecurityPenetrationTestsControllerGetEventsV1,
  );
  tool(
    tool$securityPenetrationTestsSecurityPenetrationTestsControllerGetReportV1,
  );
  tool(tool$securityPenetrationTestsSecurityPenetrationTestsControllerGetPdfV1);
  tool(tool$securityPenetrationTestsPentestFindingContextsControllerListV1);
  tool(tool$securityPenetrationTestsPentestFindingContextsControllerUpsertV1);
  tool(tool$securityPenetrationTestsPentestFindingContextsControllerRemoveV1);
  tool(
    tool$offboardingChecklistOffboardingChecklistControllerGetPendingOffboardingsV1,
  );
  tool(tool$offboardingChecklistOffboardingChecklistControllerGetTemplateV1);
  tool(
    tool$offboardingChecklistOffboardingChecklistControllerCreateTemplateItemV1,
  );
  tool(
    tool$offboardingChecklistOffboardingChecklistControllerUpdateTemplateItemV1,
  );
  tool(
    tool$offboardingChecklistOffboardingChecklistControllerDeleteTemplateItemV1,
  );
  tool(
    tool$offboardingChecklistOffboardingChecklistControllerGetMemberChecklistV1,
  );
  tool(
    tool$offboardingChecklistOffboardingChecklistControllerExportAllEvidenceV1,
  );
  tool(tool$offboardingChecklistOffboardingChecklistControllerExportEvidenceV1);
  tool(tool$offboardingChecklistOffboardingChecklistControllerCompleteItemV1);
  tool(tool$offboardingChecklistOffboardingChecklistControllerUncompleteItemV1);
  tool(tool$offboardingChecklistOffboardingChecklistControllerUploadEvidenceV1);
  tool(
    tool$offboardingChecklistOffboardingChecklistControllerGetAccessRevocationsV1,
  );
  tool(
    tool$offboardingChecklistOffboardingChecklistControllerRevokeAllVendorAccessV1,
  );
  tool(
    tool$offboardingChecklistOffboardingChecklistControllerRevokeVendorAccessV1,
  );
  tool(
    tool$offboardingChecklistOffboardingChecklistControllerUndoVendorRevocationV1,
  );

  if (deps.dynamic) {
    registerDynamicTools(deps.logger, server, getClient, toolMap, scopes);
  }

  return { server, tools };
}
